# Gausah kesini ngentot!!
# NGEDIT CMD YG BENER KONTOL!!!
# YANG HAPUS KREDIT GUA TANDAIN REPO LO

from platform import uname
from userbot import ALIVE_NAME, CMD_HELP
from userbot.events import register

# ================= CONSTANT =================
DEFAULTUSER = str(ALIVE_NAME) if ALIVE_NAME else uname().node
# ============================================

@register(outgoing=True, pattern='^.roas1(?: |$)(.*)')
async def typewriter(typew):
    typew.pattern_match.group(1)
    await typew.edit("**EH MANUSIA HARAM YANG KERJAANYA REBAHAN, GAUSAH SOK SOK MENILAI HIDUP ORANG DEH LO BANGSAT, LO SENDIRI AJA GA MAMPU BUAT MAKAN GOBLOK KARNA LU GEMBEL KERJA LO PASTI JADI MANUSIA SILVER YANG KAN, NAH MAKANYA DARIPADA KEBANYAKAN NGURUSIN HIDUP ORAMG, MENDING LU CAT BADAN LU BURUAN ABISTU KERJA DAH NGEMIS NGEMIS KALO GAK MATUNG DI PINGGIR JALAN, YAHAHA KAYA BOCAH GA PUNYA KREATIFITAS ATAU MEMANG LO PUNYA KELAINAN DISABILITAS, YANG KELIATAN IDIOT TUU, PASTI JUGA LU LULUSAN SLB YAKAN BAGIAN ORANG ORANG YG KENA GANGGUAN JIWA ATAU PUNYA KELAINAN TU YKANN YAHAHAHAH WAHYOUEEEE🤪🤪**")


@register(outgoing=True, pattern='^.roas2(?: |$)(.*)')
async def typewriter(typew):
    typew.pattern_match.group(1)
    await typew.edit("**INI NI KALO ANAK LONTE BERHASIL DI LAHIRKAN ANJING, EMAK LO GABISA GUGURIN DAN LO LAHIR SEBAGAI ANAK HARAM, KASIAN BANGET LO ANJING DARI MASA KANDUNGAN LO DI EMAK LO, UDAH GADA BAPAK, YA IYALAH ANJING ORANG ANAK LONTE, TUBUH LO ITU ADALAH CAMPURAN DARI SEMUA PELANGGAN EMAK LO NGENTOD, NAH KEBETULAN PAS KEBABLASAN EMAK LO LUPA MINUM PIL KB, JADI HAMIL KAN, UDAH LA NGENTOD MENDING LO BUNUH DIRI AJA, GA PANTES BANGET LO DI DUNIA INI ANJING!!!**")


@register(outgoing=True, pattern='^.roas3(?: |$)(.*)')
async def typewriter(typew):
    typew.pattern_match.group(1)
    await typew.edit("**WOI ALIANSI SAMPAH, NI DENGERIN YA, GC LO SEPI PASTI KAN, MAKANYA LO NGERUSUH DI GC ORANG TERUS NGAJAK WAR MANA PAKE CUAN LAGI, GUA TAU LU NGAJAK MAIN CUAN PASTI KARNA EKONOMI KELUARGALO LAGI RENDAH ANJING, YA IYALAH BAPAK LO PENGANGGURAN, EH GA DA BAPA KAYANYA, NAH EMAK LO LUMPUH KERJAAN NYA REBAHAN, MAU KEKAMAR MANDI AJA HARUS DI GOTONG KAN, YAHAHA CACAT BANGET ANJING, LO JUGA TERMASUK ORANG CACAT, MANA BIBIR SUMBING TANGAN TREMOR, UDAH COCOK BGT BUAT LO MATI BERDUA EMAK LO YAHAHAH NGENTOD ALIANSI SAMPAH!!!**")


@register(outgoing=True, pattern='^.roas4(?: |$)(.*)')
async def typewriter(typew):
    typew.pattern_match.group(1)
    await typew.edit("**MASIH JAMAN NGERUSUH SANA SINI, TERUS PAS DI LADENIN MALAH LARI?, KALO BRANI NGAJAK WAR ORANG YA PAKE KONSEKUENSI LAH TOLOL, KALO CUMA NGATA NGATAIN BEGITU, BOCIL FF JUGA BISA TOLOL, DAN KALO NGAJAK WAR TAPI ALIBI MULU, DI AJAKIN PAKE KONSEKUENSI KAGAK MAO, DI TANTANG MAIN SESI KABUR KABURAN MULU, MENDING LO WAR AJA SAMA BOCAH TK TOLOL, BRANI WAR LGSG AJA KE ALFAM BEGO, ITU JUGA KALO LU BRANI YA, KALO CUPU MAH BUBARIN AJA TU ALIANSI LO YG GA BERGUNA ITU ANIJINGGGGG!!!!**")


@register(outgoing=True, pattern='^.roas5(?: |$)(.*)')
async def typewriter(typew):
    typew.pattern_match.group(1)
    await typew.edit("**NIH YA ANAK BABI, GUA KASIH TAU KE LU NIH, LU ITU DISINI CUMA JADI KACUNG GUA NGENTOD, YANG SABAN HARI GUA INJEK INJEK TU BATANG LEHER LU, YG TIAP HARI GUA SURUH SURUH NGELAPIN KAKI GUA, GAUSAH SOK KERAS TOLOL, BAPAK LO LAGI MULUNG NOH DI PEREMPATAN, NUNGGUIN SAMPAH SAMPAH PLASTIK TOLOL, MANA PAKE BAJU PARTAI UDH DEKIL BAT KUMEL ANJING KAYA MASA DEPAN LO YG SURAM, JANGAN BELAGU APA, GUA TAU LO SKOLA CUMA SAMPE LULUSAN SD KAN? YAHAHA KETAWAN BANGET DARI NASIB LU YG MENGENASKAN.**")


@register(outgoing=True, pattern='^.roas6(?: |$)(.*)')
async def typewriter(typew):
    typew.pattern_match.group(1)
    await typew.edit("**YA AMPUN, UMUR UDAH TUA MAO MATI UDAH BAU TANAH ANJING, MASIH AJA NYENGGOL SANA SINI, PIKIRIN AJA KISAH HIDUP LU YG KELAM SAMPEL SEKARANG TOLOL, BANTUIN KEK KELUARGA LU YG KEKURANG EKONOMI, NGAPAIN KEK JUAL DIRI KEK, BIAR ADA HASIL BEGO, GUA SEBENARNYA KASIHAN SAMA LU SIH, UDAH JELEK ITEM MUKA UDAH KEK LINTINGAN DAKI BEGITU, BANGSAT BANGET NAJIS DEH GUA AMA LU.**")


@register(outgoing=True, pattern='^.roas7(?: |$)(.*)')
async def typewriter(typew):
    typew.pattern_match.group(1)
    await typew.edit("**UDAH LAH, MENDING LO CABUT AJA DARI SINI, SOAL NYA GUA GAMAU ANJING LIAT MANUSIA SAMPAH KAYAK LO ADA DI TELEGRAM, LEBIH TEPAT NYA MENDING LO DOWNLOAD MICHAT NAH ABIS TU LU NGELOTE ANJING, COCOK BANGET SOAL NYA BUAT LO ASU!!!!**")


@register(outgoing=True, pattern='^.roas8(?: |$)(.*)')
async def typewriter(typew):
    typew.pattern_match.group(1)
    await typew.edit("**DARI PENILAIAN GUA NI YA, KEBANYAKAN DARI LO ITU CUMA JELEK NYA DOANG ANJING KAGA ADA BAGUS BAGUS NYA LO DI MATA GUA, KEK LIAT TAI BABI GUA KALO LIATIN MUKA LO, YA IYALAH ORANG TERLAHIR DARI EMAK YG PENYAKITAN, MEMEK NYA KENA RAJA SINGAN YAHAHA, TERLALU KASAR GUA, MAAF YA, EH TAPI EMG PANTES LO DI KATA KATAIN KAYA GITU, UDAH COCOK BANGET LO NYUSUL BAPAK LO SANA KE KUBURAN, MANA GA PERNAH DI DOAIN LAGI TU PASTI BAPAK LO YKAN, LAGI DI SIKSA MALAIKAT, GA ADA PENGAMPUNAN GARA GARA LO GA PERNAH DOA, YA GIMANA MAO DOA ORANG SELAMA LO HIDUP KERJAAN NYA CUMA MAEN TELEGRAM DOANG, NGEBACOT DOANG ANJINGG, GA PERNAH NGAJI GA PERNAH BELAJAR AGAMA PASTI, MAKANYA LO TUH MIS ATTITUDE, MIS AKHLAK PULA ADUHHHH ANAK NGENTOD.**")


@register(outgoing=True, pattern='^.roas9(?: |$)(.*)')
async def typewriter(typew):
    typew.pattern_match.group(1)
    await typew.edit("**GAUSAH SOK SOK AN NYENGGOL GUA ANJING, TAR GUA AJAKIN SESI, LO LARI, GUA AJAKIN BIKIN KONSEKUENSI LO BANYAK ALIBI, YAHAHA SSMPAH BANGET LO NGENTOD, UDAH LAH MENDING LO PERGI JAUH JAUH DARI MATA GUA, JIJI BAT LIATNYA CUIHHKKKK.**")


@register(outgoing=True, pattern='^.roas10(?: |$)(.*)')
async def typewriter(typew):
    typew.pattern_match.group(1)
    await typew.edit("**NIH NIH GUA KASIH BANSOS DEH BUAT LO, LO BELOM PERNAH NGERASAIN MSKSN SARDEN KAN? YAHAHA KASIAN BANGET HIDUP LU YG SABAN HARI MAKAN NASI SAMA GAREM DOANG ANJING, MAKANYA OTAK LO BEGOOO, MANA PASTI SKALINYA MAKAN ENAK, LO CUMA GORENG TELOR AJA KAN, PAKE MICIN YG BANYAK, EMG BOCAH MICIN ANJING, RADA TOLOL SI GUA KALO NGELADENIN LO YG CUMA BISA NGANG NGENG NGONG DOANG ANJING, YA IYA KARNA LO, EMG GA ADA BAKAT APA APA ANJING DI TELEGRAM, CABUT BURUAN CABUT TAR GUA GBAN AMA GUA LO NGENTOD.**")


CMD_HELP.update({
    "roas":
    ".roas1\
\nUsage: roasting Satu.\
\n\n.roas2\
\nUsage: Roasting Dua.\
\n\n.roas3\
\nUsage: Roasting Tiga.\
\n\n.Roas4\
\nUsage: Roasting Empat.\
\n\n.roas5\
\nUsage: Roasting Lima.\
\n\n.Roas6\
\nUsage: Roasting Enam.\
\n\n.roas7\
\nUsage: Roasting Tujuh.\
\n\n.roas8\
\nUsage: Roasting Delapan.\
\n\n.roas9\
\Usage: Roasting Sembilan.\
\n\n.roas10\
\nUsage: Roasting Sepuluh."
})
