ROAS = [
    "UDAH GAK GUNA",
    "DI TAMBAH HINA",
    "MERANA PULA, LENGKAP KALI KEHIDUPAN KAU MACAM SINETRON DI INDOSIAR YANG SERING DI GUNA GUNA.",
]
    

#sukasuka
SUKASUKA = [
    "MINIMAL NIH YA LU MANDI DULU",
    "TERUS LU MINTA BEDAKIN SAMA EMAK LU",
    "ABIS ITU BARU DAH LU NGAKU NGAKU KALO LU TUH PANJAHAT KELAMIN",
]

#dibuat oleh GARAMIJO
ram_a = "YAELAHH DONGOO KALI KAU DEKKUH"
ram_b = "BABU ALIANSI BANYAK KALII GAYANYA,UDAH GAK KERAS MASIH AJA BANYAK BACOTT"
ram_c = "CANTIKK SII TAPI SAYANGNYA BABU ALIANSI"
ram_d = "LAGI NYARI KOSAKATA YA DEKKUH DI GC LAINN, BHAKSSS"
ram_e = "EH BABU,KALO DI BILANGIN AMA YANG LEBIH TUA TUH JANGAN BATU NGENTOT,OTAK LU TUH LEMAH GOBLOK, DI KASIH TAU MALAH BATU NGENTOT KOSAKATA MASIH CARI DI GC LAEN BLAGUNYA BUKAN MAEN DEKKUHH !" 
ram_f = "MENDING LU BUKA YOUTUBE CARI TUTORIAL KIYOMASA, DARI PADA TYPINGAN SAMPAH KAYA LU TOLOL, GAK BIKIN GEMETER"
ram_g = "GAK JELASS KONTOL MASIH KECIL,BIJINYA SEUKURAN KERIKIL"
ram_h = "HABIS COLI YA DEKKUH, PANTESSSS NAMBAH DONGO !"
ram_i = "ITU KAN KOSAKATANYA NGAMBIL !"
ram_j = "JANGAN KERAS-KERAS DEK, KERASNYA LU TUH CUMA DI DEPAN CEWE DOANG JADI JATOHNYA CAPER NGENTOT !"
ram_k = "KALO CUMA LU DOANG MAH IBARAT KATA KAYA GW LAWAN ANAK TK !"
ram_l = "Wa'alaikumsalam, ada apa?"
ram_m = "MUKA LU NGAMBIL DI PINTEREST KAN??GAK BERANI PAKE MUKA HINA LU YA TOLOL"
ram_n = "NIH DIA YANG GW TUNGGUIN DARI KEMAREN, DATENG JUGA SI BABU WUAHAHAHA"
ram_o = "ORANG MAH KALO GAK GUNA MINIMAL MAH MIKIRR DEKKUH, UDAH GAK GUNA BEBAN PULA MENDING MAEN POU AJA BERSIHIN TAI YANG KAYA MUKA LU, BHAKSS"
ram_p = "Assalamu'alaikum"
ram_q = "QUNYUKKKK BANYAK KALI LAGANYA, TAPI JATOHHNYA CAPER SIHH, CUIHH!"
ram_r = "RASANYA KOK KAYA GAK ADA APA APA YA, PADAHAL LU MAH UDAH BACOT PANJANG KALI LEBAR TAPI BELOM KERASA HADEHH"
ram_s = "SAYANG-SAYANG MENTAL LU NANTI DOWN KALO LAWAN GUA, BHAKSSS"
ram_t = "TERIMA KASIH KEK MINIMAL NGENTOT,UDAH GW KASIH TEMPAT LU UNTUK CAPER SANA SINI TOD"
ram_u = "UDAH HINA,BANYAK GAYA NGENTOT MASIH MENDING GW LADENIN"
ram_v = "NORAK ANJING MAENIN BOT TERUS KONTOL, NANTI DELAY YANG DI SALAHIN BOT NYA MEMEK"
ram_w = "WAR-WAR TAI ANJING BABI,CUMA DATENG MODAL MENTAL TEMPE AJA BELAGU"
ram_x = "HAPENYA KENTANG,SOK MENANTANG"
ram_y = "MUKA LU TUH UDAH HINA, JADI JANGAN DIBUAT NAMBAH HINA NANTI HIDUP LU JADI GAK GUNA TOLOLL"
ram_z = "BANYAK GAYA TAPI BUKAN ORANG KAYA,BAPAK LU MASIH PAKE BAJU PARTAI DAPET DARI SOGOKAN NYOBLOS AJA UDAH GEDE LAGANYA"

PAKBOY = [
    "AKU CUMA MAU AMA KAMU DOANG ",
    " DI TAMBAH KAMU TUH CANTIK",
    "Itu lah PAKBOY kelas mengontol.",
]
    

#GENIT
GENIT = [
    "AKU MEMANG MANUSIA BIASA ",
    " YANG TAK SEMPURNA DAN KADANG SALAH",
    "NAMUN DI HATIKU HANYA SATU CINTA UNTUKMU, LUAR BINASA",
]


ram_ab = "ANDAIKA AKU BISA MENDAPATKANMU...."
ram_bc = "BOLEH GAK SI AKU NIH BERUSAHA MENDAPATKAN SESEORANG,YAITU KAMU..."
ram_cd = "CUMA MAU NGUNGKAPIN PERASAAN AJA SUSAHNYA MINTA APUN KE KAMU"
ram_de = "DULU PERNAH KU MENJADI SASIMO DAN PAKBOY, GAK TAHU KENAPA DAPET KAMU AKU HANYA INGIN BERSAMA KAMU AJA"
ram_ef = "aku akan selalu menyukaimu" 
ram_fg = "JANGAN LUPA UNTUK HAPPY KIYOWO DI SETIAP HARINYA KAKAKK :)"
ram_gh = "JIKA MEMANG AKU TIDAK BISA MENDAPAT KAMU,TOLONG DI PERHATIKAN KEBERADAAN DIRIKU YANG DULU PERNAH MENGISI KEGABUTAN KAMU DENGAN SEMUA KEBODOHAN YANG KU PUNYA"
ram_hi = "AWASS NANTI JADI SUKAA !"
ram_ij = "RUN!....LARII ADA YANG BUCINN !"
ram_jk = "JIMATT PEMIKAT CEWEEE....CIATTTT"
ram_kl = "kalo kita selalu tiba-tiba **CINLOK** BAGAIMANA?"
ram_lm = "Wa'alaikumsalam, ada apa cantik?"
ram_mn = "MASA LALU ITU HARUS DI INGET KAK,SUPAYA NANTI KALO TIBA-TIBA KITA LUPA DEKETIN ORANG KAN BISA DI INGET KMRN KITA PDKTNYA GIMANA HEHEHE"
ram_no = "NIH DIA YANG GW TUNGGUIN DARI KEMAREN, DATENG JUGA SI BABU WUAHAHAHA"
ram_op = "Oh jadi ini yang sering membuat kau selalu ada di pikiran aku?"
ram_pq = "Assalamu'alaikum"
ram_qr = "kamu tersakiti, dan aku pun juga tersakiti, bagaimana kalo kita saling melengkapi"
ram_rs = "rasa itu selalu timbul ketika kita saling tertawa, chat, berbicara dan aku selalu menginginkan dirimu saja"
ram_st = "sayang?? gorengannya jatoh tuh belom 5 menit. Sayang-sayang kalo di buang:V"
ram_tu = "aku yang dulu bukan aku yang sekarang, karena aku bisa merubah kekurangan aku menjadi sesuatu kelebihan yang ku miliki"
ram_uv = "Ciee yang lagi menyukai tetapi tidak tau mau berbuat apa"
ram_vw = "aku bukan Joker kak, yang abis tersakiti lalu jahat hehehe"
ram_wx = "kata orang itu **JANGAN JADI PELANGI UNTUK ORANG YANG BUTA WARNA**, kalo kata aku si mending jadi awan aja kak yang gak tau apa apa wkwk"
ram_xy = "kalo di free fire ada **ONESHOOT**, kalo di sini ada **ONE HEART**"
ram_yz = "ternyata oh ternyata bener kata orang, **KALO JODOH TUH GAK AKAN KEMANA**"
ram_z1 = "jangan mau jadi SCTV kak, nanti satu untuk semua jatohnya nanti jadi **LONTE**"